# Generated by Django 4.0.4 on 2022-05-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_ispublished_alter_apartment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(max_length=30, verbose_name='Apartment Description'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(max_length=50, upload_to='', verbose_name='Apartment Image'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Apartment Name'),
        ),
    ]
