# Generated by Django 4.0.4 on 2022-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_location_apartment_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.CharField(max_length=15, null=True, verbose_name='Apartment Price'),
        ),
    ]
