# Generated by Django 4.0.4 on 2022-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_alter_apartment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='square_meters',
            field=models.CharField(max_length=15, null=True, verbose_name='How Many Square Meters'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Apartment Description'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Apartment Name'),
        ),
    ]
