# Generated by Django 4.0.4 on 2022-05-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_apartment_apartment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='color',
            field=models.CharField(max_length=15, null=True, verbose_name='Apartment Color'),
        ),
    ]
